import React from 'react';
import type { Metadata } from 'next';

import { Footer } from '@/widgets/footer/ui/footer';
import { Header } from '@/widgets/header/ui/header';

import './globals.css';

import { Providers } from '@/app/providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={'antialiased'}>
        <Providers>
          <Header />
          <main className={'flex-1 container mx-auto px-5'}>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
